### ISSUE TITLE
Problems on RaspberryPi, Raspbian

### ISSUE THREAD

**Issue by SpenioPantollor** [rhymeswithmogul/aprs-weather-submit#3]
When I install this repository in to raspberry and try to RUN, cmd always shows this message

![image](https://user-images.githubusercontent.com/46783480/120386958-f79ce300-c331-11eb-8275-0197e73c0f06.png)

**Comment by rhymeswithmogul** [comment]
I don't have a Raspberry Pi to test, but I’ll take a look at this.

**Comment by KR4DIO** [comment]
I fixed this issue a while back but forgot to submit a pull request. Casting the return value of getopt_long() from int to char turns the -1 “all done” flag into 255 on ARM systems.

**Comment by rhymeswithmogul** [comment]
I noticed this and think I got it in the last release.  Can you re-test?
