### ISSUE TITLE
issue in order aprs string

### ISSUE THREAD

**Issue by pd9mwo** [rhymeswithmogul/aprs-weather-submit#6]
look like there is an issue with the order to send to APRS-IS

PD9MWO-4>APRS,TCPIP*:@171407z5216.39N/00437.37E_110/004**t049g012**P000h83b10256L063Xaprs-weather-submit/1.4
but must be
PD9MWO-4>APRS,TCPIP*:@171407z5216.39N/00437.37E_110/004**g012t049**P000h83b10256L063Xaprs-weather-submit/1.4

the raw packets on aprs.fi 
**GOOD**
2022-01-17 15:09:09 CET: PD9MWO-4>APRS,TCPIP*,qAC,T2EDM:@171408z5216.39N/00437.37E_049/004**g012t049**P000h83b10256L062Xaprs-weather-submit/1.4

**ISSUE**
2022-01-17 15:11:31 CET: PD9MWO-4>APRS,TCPIP*,qAC,T2EDM:@171411z5216.39N/00437.37E_084/007**t049g002**P000h83b10256L061Xaprs-weather-submit/1.4

the order is wrong here
can you please fix this ??

many thanks in advance
menno
pd9mwo

**Comment by rhymeswithmogul** [comment]
Thanks!  Let me review this and I'll get back to you.

**Comment by rhymeswithmogul** [comment]
It seems odd that APRS.fi would ignore the gust speed if it comes after the temperature -- but that wouldn't be the first time I've had to deviate from the specification to make that (wonderful) site happy.  Could you link me to a raw packet that was not processed correctly?

**Comment by pd9mwo** [comment]
Thx
the raw item thats in my first port

menno

**Comment by rhymeswithmogul** [comment]
APRS.fi is not following the specification correctly, but I suppose I can switch the `g` parameter to be first.

**Comment by pd9mwo** [comment]
> APRS.fi is not following the specification correctly, but I suppose I can switch the `g` parameter to be first.

or use my solution in the second post ;-)

**Comment by rhymeswithmogul** [comment]
Sorry, @pd9mwo. I could have sworn that I worked around this in version 1.5.  It's fixed now.
