### ISSUE TITLE
configure?

### ISSUE THREAD

**Issue by surfrod** [rhymeswithmogul/aprs-weather-submit#7]
Instructions say to run "./configure", however there is no configure supplied in pull.

**Comment by marsolla** [comment]
Try this

> sudo apt install autoconf automake libtool
> autoreconf -i
> ./configure
> make
> make install (if you want to install in your system path)

ps> use "make clean" to clean binaries before re-compile

**Comment by surfrod** [comment]
Thanks, will give that a try!

**Comment by rhymeswithmogul** [comment]
Thank you both!  I'm still learning configure scripts.  I will take a look at this code and see if I can improve the build system.
